name: Run Jupyter Notebook

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install gh

      - run: gh auth login

      - run: gh codespace jupyter -c supreme orbit
