name: Create Jupyter Codespace

on:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi giờ vào phút 0

jobs:
  create-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Create Jupyter Codespace
        run: gh codespace jupyter -R thanhtayt/chatgpt_telegram_bot
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
