name: Start Codespace on Update
on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu cần
jobs:
  start_codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start Codespace
        run: |
          chmod +x start_codespace.sh
          ./start_codespace.sh
        env:
          GH_TOKEN: ${{ secrets.GTOKEN }}
