name: Create Jupyter Codespace

on:
  workflow_dispatch:

jobs:
  create-codespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Create Jupyter Codespace
        run: gh codespace jupyter --web
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
